AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  SAM Template for LogStreamProcessor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

# TODO Replace 2 log groups with a list of log groups
Parameters:
  EmailAddress:
    Type: String
    Description: Email address to receive SNS notifications
  LogGroupName1:
    Type: String
    Description: Name of the first CloudWatch Log Group to subscribe to
  LogGroupName2:
    Type: String
    Description: Name of the second CloudWatch Log Group to subscribe to
  MatchPattern:
    Type: String
    Description: Pattern to match in the log streams
  DedupWindowSeconds:
    Type: Number
    Description: Size of the sliding window in seconds
  IsRollingWindow:
    Type: String
    Description: Whether to roll the dedup window each time a new message is received

Resources:
  LogStreamProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: logstreamprocessor/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - arm64
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt LogStreamProcessorRole.Arn
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref LogStreamProcessorSNSTopic
          DEDUP_WINDOW_SECONDS: !Ref DedupWindowSeconds
          IS_ROLLING_WINDOW: !Ref IsRollingWindow
      Events:
        ErrorLine1:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref LogGroupName1
            FilterPattern: !Ref MatchPattern
        ErrorLine2:
          Type: CloudWatchLogs
          Properties:
            LogGroupName: !Ref LogGroupName2
            FilterPattern: !Ref MatchPattern

  LogMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: log_messages
      AttributeDefinitions:
        - AttributeName: message
          AttributeType: S
      KeySchema:
        - AttributeName: message
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  DynamoDBAutoscaleRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${AWS::StackName}-DynamoDBAutoscaleRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: DynamoDBAutoscalePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:DescribeTable"
                  - "dynamodb:UpdateTable"
                  - "cloudwatch:PutMetricAlarm"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:DeleteAlarms"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:SetAlarmState"
                  - "sns:Publish"
                Resource: "*"

  LogMessagesTableReadScalingTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Sub "table/${LogMessagesTable}"
      RoleARN: !GetAtt DynamoDBAutoscaleRole.Arn
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: "dynamodb"

  LogMessagesTableReadScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: "LogMessagesTableScalingPolicy"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref LogMessagesTableReadScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBReadCapacityUtilization"

  LogMessagesTableWriteScalingTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    Properties:
      MaxCapacity: 10
      MinCapacity: 1
      ResourceId: !Sub "table/${LogMessagesTable}"
      RoleARN: !GetAtt DynamoDBAutoscaleRole.Arn
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: "dynamodb"

  LogMessagesTableWriteScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: "LogMessagesTableScalingPolicy"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref LogMessagesTableWriteScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBWriteCapacityUtilization"

  LogStreamProcessorSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-sns-topic"
      DisplayName: LogStreamProcessor SNS Topic
      Subscription:
        - Protocol: email
          Endpoint: !Ref EmailAddress

  LogStreamProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !GetAtt LogMessagesTable.Arn
        - PolicyName: SNSPublishAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref LogStreamProcessorSNSTopic
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  LogStreamProcessorFunction:
    Description: "Log Processor Lambda Function ARN"
    Value: !GetAtt LogStreamProcessorFunction.Arn

  LogMessagesTable:
    Description: "Log Messages DynamoDB Table ARN"
    Value: !GetAtt LogMessagesTable.Arn

  LogStreamProcessorSNSTopic:
    Description: "Log Processor SNS Topic ARN"
    Value: !Ref LogStreamProcessorSNSTopic
